### ISSUE TITLE
[Question] Skip confirmation for mtx --registry-offboard

### ISSUE THREAD

**Issue by NathanHayoun** [cap-js-community/mtx-tool#20]
Hello, 
I'm using mtx-tools version 0.7.7 and I would like to make a python script (automatically executed) that allows to offboard some tenant with command : "mtx --registry-offboard TENANT_ID". 
Only, we are obliged to type "Yes" to confirm.

 Is there a feature that allows to not need to enter a confirmation, like for example with a -y flag ?  

Best Regards, 
Nathan Hayoun

**Comment by rlindner81** [comment]
For scripts you can add a `--force` option, which will always bypass the guards. You _have_ to know what you are doing then... I will add the to the docs soon.

**Comment by NathanHayoun** [comment]
It works.
Thanks a lot ! 

Best Regards,
Nathan Hayoun
