### ISSUE TITLE
Configuration for 'cds.requires.cds.xt.SaasProvisioningService' lacks mandatory property 'kind' or 'impl'

### ISSUE THREAD

**Issue by krishraheja** [cap-js-community/mtx-tool#31]
Hi Colleague,

We are just migrating from mtx to mtxs tool. We have maintained     
"cds.xt.ModelProviderService": true,
    "cds.xt.SaasProvisioningService": true,
    "cds.xt.DeploymentService": true 

in our .cdsrc.json file but during deployment, we are getting error "**Configuration for 'cds.requires.cds.xt.SaasProvisioningService' lacks mandatory property 'kind' or 'impl'**".

Not sure what is the cause. Could you please help us here in resolving this issue.

We can discuss the more details in our internal team chat/call.

Best Regards
Krishan Raheja

**Comment by rlindner81** [comment]
Hi Krishan, I think you confused [cds-mtx](https://github.tools.sap/cap/cds-mtx) and mtx-tool. There is no such things as mtxs-tool. This tool works with both cds-mtx and cds-mtxs.  For cds-mtx(s) related problems, you can open a related cap issue at: https://github.tools.sap/cap/issues/issues

**Comment by krishraheja** [comment]
Thanks Richard,

I have posed the issue in CAP repo.
