### ISSUE TITLE
Is there any plan to support @sap/mtxs?

### ISSUE THREAD

**Issue by leonzhan** [cap-js-community/mtx-tool#37]
after migration from mtx to mtxs, it seems the tool does not work, right?
If right, is there any plan to support it?

**Comment by rlindner81** [comment]
Our project is already using mtx-tool with `@sap/cds-mtxs`. Can update to the latest version and provide some example what doesn't work.

**Comment by rlindner81** [comment]
@leonzhan I'm giving you till tomorrow end of business to provide some details, or I'll close this for inactivity and unclear problem description...
