### ISSUE TITLE
mtx hdil - add column to show if hdi container is HANA native tenant

### ISSUE THREAD

**Issue by soccermax** [cap-js-community/mtx-tool#56]

**Comment by rlindner81** [comment]
Information is not externally available... I guess everyone will be native at some point.

**Comment by soccermax** [comment]
Information can be queried with:
```
GET https://service-manager.cfapps.{{landscape}}.hana.ondemand.com/v1/service_instances/<instanceGuid>/parameters
```

**Comment by rlindner81** [comment]
Currently this Hana Cloud feature is internal only. So, it doesn't make sense for our tooling.
