### ISSUE TITLE
Entering in infinite loop running mtx --registry-list

### ISSUE THREAD

**Issue by cgaillydetaurines** [cap-js-community/mtx-tool#74]
Since version 0.8.2. I enter in a infinite loop when calling mtx --registry-list command:
Don't have the issue with the version 0.8.0.

<img width="1460" alt="image" src="https://github.com/cap-js-community/mtx-tool/assets/153727562/b46f2051-a430-4895-a026-b6bd97bfe209">

BR.

**Comment by rlindner81** [comment]
Thanks for reporting this is indeed a bug that was introduced as part of recent changes. I will fix it asap.

**Comment by rlindner81** [comment]
Please re-test with version 0.8.4: https://github.com/cap-js-community/mtx-tool/releases/tag/v0.8.4

For example:
`npx @cap-js-community/mtx-tool@0.8.4 --registry-list`

**Comment by cgaillydetaurines** [comment]
Works fine.
Tx.
