### ISSUE TITLE
Token expires after 12H

### ISSUE THREAD

**Issue by cgaillydetaurines** [cap-js-community/mtx-tool#76]
Hi Team,

We get the following issue:
We have 300 subscriptions on our tenant. When running the command  mtx --registry-update-all  we have an access denied after 12H.
Any idea for a workaround ? Would it be possible to renew the token or have a parameter to increase validity time ?

Tx.

**Comment by rlindner81** [comment]
That would need some deeper analysis. From what I can see that code in --registry-update-all does respect the token's expires_in field and should get a new token when the old one expires.

Can you send the logs that you see?

**Comment by cgaillydetaurines** [comment]
04:39:29  polling job /api/v2.0/jobs/2e9bff54-b2f9-483a-a929-8f38c040eb4a with interval 10sec
04:39:38  GET https://saas-manager.mesh.cf.eu12.hana.ondemand.com/api/v2.0/jobs/2e9bff54-b2f9-483a-a929-8f38c040eb4a 200 OK (46ms)
04:39:48  GET https://saas-manager.mesh.cf.eu12.hana.ondemand.com/api/v2.0/jobs/2e9bff54-b2f9-483a-a929-8f38c040eb4a 200 OK (50ms)
04:40:00  GET https://saas-manager.mesh.cf.eu12.hana.ondemand.com/api/v2.0/jobs/2e9bff54-b2f9-483a-a929-8f38c040eb4a 200 OK (45ms)
04:40:08  GET https://saas-manager.mesh.cf.eu12.hana.ondemand.com/api/v2.0/jobs/2e9bff54-b2f9-483a-a929-8f38c040eb4a 200 OK (48ms)
04:40:18  GET https://saas-manager.mesh.cf.eu12.hana.ondemand.com/api/v2.0/jobs/2e9bff54-b2f9-483a-a929-8f38c040eb4a 200 OK (63ms)
04:40:28  GET https://saas-manager.mesh.cf.eu12.hana.ondemand.com/api/v2.0/jobs/2e9bff54-b2f9-483a-a929-8f38c040eb4a 200 OK (50ms)
04:40:40  GET https://saas-manager.mesh.cf.eu12.hana.ondemand.com/api/v2.0/jobs/2e9bff54-b2f9-483a-a929-8f38c040eb4a 200 OK (46ms)
04:40:48  GET https://saas-manager.mesh.cf.eu12.hana.ondemand.com/api/v2.0/jobs/2e9bff54-b2f9-483a-a929-8f38c040eb4a 200 OK (42ms)
04:40:58  GET https://saas-manager.mesh.cf.eu12.hana.ondemand.com/api/v2.0/jobs/2e9bff54-b2f9-483a-a929-8f38c040eb4a 200 OK (47ms)
04:41:08  GET https://saas-manager.mesh.cf.eu12.hana.ondemand.com/api/v2.0/jobs/2e9bff54-b2f9-483a-a929-8f38c040eb4a 200 OK (46ms)
04:41:18  GET https://saas-manager.mesh.cf.eu12.hana.ondemand.com/api/v2.0/jobs/2e9bff54-b2f9-483a-a929-8f38c040eb4a 200 OK (59ms)
04:41:30  GET https://saas-manager.mesh.cf.eu12.hana.ondemand.com/api/v2.0/jobs/2e9bff54-b2f9-483a-a929-8f38c040eb4a 200 OK (50ms)
04:41:38  GET https://saas-manager.mesh.cf.eu12.hana.ondemand.com/api/v2.0/jobs/2e9bff54-b2f9-483a-a929-8f38c040eb4a 200 OK (44ms)
04:41:48  GET https://saas-manager.mesh.cf.eu12.hana.ondemand.com/api/v2.0/jobs/2e9bff54-b2f9-483a-a929-8f38c040eb4a 200 OK (48ms)
04:41:58  GET https://saas-manager.mesh.cf.eu12.hana.ondemand.com/api/v2.0/jobs/2e9bff54-b2f9-483a-a929-8f38c040eb4a 200 OK (47ms)
04:42:08  GET https://saas-manager.mesh.cf.eu12.hana.ondemand.com/api/v2.0/jobs/2e9bff54-b2f9-483a-a929-8f38c040eb4a 200 OK (44ms)
04:42:18  GET https://saas-manager.mesh.cf.eu12.hana.ondemand.com/api/v2.0/jobs/2e9bff54-b2f9-483a-a929-8f38c040eb4a 200 OK (50ms)
04:42:31  GET https://saas-manager.mesh.cf.eu12.hana.ondemand.com/api/v2.0/jobs/2e9bff54-b2f9-483a-a929-8f38c040eb4a 200 OK (62ms)
04:42:39  GET https://saas-manager.mesh.cf.eu12.hana.ondemand.com/api/v2.0/jobs/2e9bff54-b2f9-483a-a929-8f38c040eb4a 200 OK (54ms)
04:42:39  PATCH https://saas-manager.mesh.cf.eu12.hana.ondemand.com/saas-manager/v1/application/tenants/f8ae1ded-3417-4247-a807-c751309c1b54/subscriptions 202 Accepted (192ms)
04:42:39  response: Job for update subscription of application: cloud-conso-dev-grdcmaster-grdcsaas and tenant: f8ae1ded-3417-4247-a807-c751309c1b54, was created
04:42:39  polling job /api/v2.0/jobs/6d330808-2df9-46e7-ab8e-22af55e1e4bc with interval 10sec
04:42:51  GET https://saas-manager.mesh.cf.eu12.hana.ondemand.com/api/v2.0/jobs/6d330808-2df9-46e7-ab8e-22af55e1e4bc 200 OK (47ms)
04:42:59  GET https://saas-manager.mesh.cf.eu12.hana.ondemand.com/api/v2.0/jobs/6d330808-2df9-46e7-ab8e-22af55e1e4bc 200 OK (55ms)
04:43:09  GET https://saas-manager.mesh.cf.eu12.hana.ondemand.com/api/v2.0/jobs/6d330808-2df9-46e7-ab8e-22af55e1e4bc 200 OK (54ms)
04:43:19  GET https://saas-manager.mesh.cf.eu12.hana.ondemand.com/api/v2.0/jobs/6d330808-2df9-46e7-ab8e-22af55e1e4bc 200 OK (53ms)
04:43:29  GET https://saas-manager.mesh.cf.eu12.hana.ondemand.com/api/v2.0/jobs/6d330808-2df9-46e7-ab8e-22af55e1e4bc 200 OK (62ms)
04:43:41  GET https://saas-manager.mesh.cf.eu12.hana.ondemand.com/api/v2.0/jobs/6d330808-2df9-46e7-ab8e-22af55e1e4bc 200 OK (49ms)
04:43:49  GET https://saas-manager.mesh.cf.eu12.hana.ondemand.com/api/v2.0/jobs/6d330808-2df9-46e7-ab8e-22af55e1e4bc 200 OK (46ms)
04:43:59  GET https://saas-manager.mesh.cf.eu12.hana.ondemand.com/api/v2.0/jobs/6d330808-2df9-46e7-ab8e-22af55e1e4bc 200 OK (50ms)
04:44:09  GET https://saas-manager.mesh.cf.eu12.hana.ondemand.com/api/v2.0/jobs/6d330808-2df9-46e7-ab8e-22af55e1e4bc 200 OK (51ms)
04:44:19  GET https://saas-manager.mesh.cf.eu12.hana.ondemand.com/api/v2.0/jobs/6d330808-2df9-46e7-ab8e-22af55e1e4bc 200 OK (43ms)
04:44:32  error: got bad response 401 from https://cloud-conso-dev.authentication.cert.eu12.hana.ondemand.com/oauth/token
04:44:32  {"error":"invalid_client","error_description":"Client Authentication failed."}

**Comment by cgaillydetaurines** [comment]
Hi Richard,
You get the point, there was a deployment that occurred during the update.
Thank you for your insights

**Comment by rlindner81** [comment]
> Hi Richard, You get the point, there was a deployment that occurred during the update. Thank you for your insights

Thanks. I think 12h is still excessively long. I will try and add concurrency to the processing of these registry requests. We do them serially for now to avoid overloading the registry endpoint, but I'm sure it can do some concurrency.
https://github.com/cap-js-community/mtx-tool/issues/77
