### ISSUE TITLE
How to set encryption mode as 'DEDICATED_KEY' while enabling HANA native tenants using command "mtx --hdi-enable-native"?

### ISSUE THREAD

**Issue by mandoliya** [cap-js-community/mtx-tool#89]
We are able to successfully make use of command "mtx --hdi-enable-native" to enable native HANA tenants for HDI Containers as shown below.

![image](https://github.com/user-attachments/assets/7888ed8f-c974-4091-b24d-75f48ea265c2)

![image](https://github.com/user-attachments/assets/71541378-2c19-4df4-b553-303f5b82c880)

However, we are looking for a way to enable encryption mode as 'DEDICATED_KEY' as well while executing the above command. Hence, we attempted executing the command "mtx --hdi-enable-native DEDICATED_KEY" as shown below. But this only led to some 'GET' calls and no PATCH call.

![image](https://github.com/user-attachments/assets/3758c4cf-4faa-4d79-a7d9-842b624f338b)

Is there any extension to command "mtx --hdi-enable-native" to set encryption mode as 'DEDICATED_KEY'?

**Comment by rlindner81** [comment]
As discussed, this command is not fully released and supported for now.
